/*
 * Copyright (c) 2019 Zavarov
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package vartas.reddit.comment._ast;

import de.monticore.literals.mccommonliterals._ast.ASTSignedBasicLongLiteral;
import de.monticore.literals.mccommonliterals._ast.ASTStringLiteral;
import vartas.MonticoreEscapeUtils;
import vartas.reddit.Comment;
import vartas.reddit.comment._symboltable.LongEntrySymbol;
import vartas.reddit.comment._symboltable.StringEntrySymbol;

import java.time.LocalDateTime;
import java.time.ZoneOffset;

/**
 * This class makes the Comment class generated by MontiCore compatible with
 * the {@link Comment}.
 */
public class ASTComment extends ASTCommentTOP implements Comment {
    /**
     * @return the time in UTC when the comment was made
     */
    @Override
    public LocalDateTime getCreated() {
        long seconds = Long.parseUnsignedLong(resolveString(ASTCommentEnum.CREATED));
        return LocalDateTime.ofEpochSecond(seconds, 0, ZoneOffset.UTC);
    }
    /**
     * @return the author's name of the comment.
     */
    public String getAuthor() {
        return resolveString(ASTCommentEnum.AUTHOR);
    }

    /**
     * @return the unique comment id.
     */
    public String getId() {
        return resolveString(ASTCommentEnum.ID);
    }

    /**
     * @return the subreddit the submission was made in.
     */
    public String getSubreddit() {
        return resolveString(ASTCommentEnum.SUBREDDIT);
    }

    /**
     * @return The upvotes of the comment minus the downvotes.
     */
    public int getScore() {
        return (int)resolveLong(ASTCommentEnum.SCORE);
    }

    /**
     * @return the name of the parent submission this comment is a part of.
     */
    public String getSubmissionTitle() {
        return resolveString(ASTCommentEnum.SUBMISSIONTITLE);
    }

    /**
     * @return the id of the parent submission this comment is a part of.
     */
    public String getSubmission() {
        return resolveString(ASTCommentEnum.SUBMISSION);
    }
    /**
     * @return a hash code based on the id of the comment.
     */
    @Override
    public int hashCode(){
        return getId().hashCode();
    }
    /**
     * Two comments are equal if they have the same id.
     * @param o An object this comment is compared to.
     * @return True if the object is a comment with the same id.
     */
    @Override
    public boolean equals(Object o){
        if(o instanceof Comment){
            Comment comment = (Comment)o;
            return comment.getId().equals(this.getId());
        }else{
            return false;
        }
    }

    private String resolveString(ASTCommentEnum key){
        return getSpannedScope()
                .resolveStringEntryLocally(key.name())
                .map(StringEntrySymbol::getAstNode)
                .map(ASTStringEntry::getValue)
                .map(ASTStringLiteral::getValue)
                .map(MonticoreEscapeUtils::unescapeMonticore)
                .orElseThrow();
    }

    private long resolveLong(ASTCommentEnum key){
        return getSpannedScope()
                .resolveLongEntryLocally(key.name())
                .map(LongEntrySymbol::getAstNode)
                .map(ASTLongEntry::getValue)
                .map(ASTSignedBasicLongLiteral::getValue)
                .orElseThrow();
    }
}
