submission {
    Author = "author"
    Id = "id"
    Linkflairtext = "linkFlairText"
    Subreddit = "subreddit"
    Nsfw = true
    Spoiler = true
    Score = 1L
    Title = "title"
    Created = "1"
    Selftext = "selfText"
    Thumbnail = "thumbnail"
    Url = "url"
    Permalink = "permalink"
}

submission {
    Author = "author"
    Id = "id"
    Subreddit = "subreddit"
    Nsfw = true
    Spoiler = true
    Score = 1L
    Title = "title"
    Created = "1"
    Url = "url"
    Permalink = "permalink"
}