/*
 * Copyright (c) 2019 Zavarov
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package vartas.reddit.submission._ast;

import de.monticore.literals.mccommonliterals._ast.ASTBasicLongLiteral;
import de.monticore.literals.mccommonliterals._ast.ASTSignedNatLiteral;
import vartas.reddit.Submission;
import vartas.reddit.submission._symboltable.*;

import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.Optional;

import static vartas.reddit.MonticoreEscapeUtils.unescapeMonticore;
/**
 * This class makes the Submission class generated by MontiCore compatible with
 * the {@link Submission}.
 */
public class ASTSubmission extends ASTSubmissionTOP implements Submission {
    /**
     * @return the name of the submission author.
     */
    public String getAuthor() {
        Optional<AuthorLiteralSymbol> symbol = getSpannedScope().resolveAuthorLiteralLocally("author");

        return unescapeMonticore(symbol.get().getAstNode().get().getStringLiteral().getValue());
    }

    /**
     * @return The unique submission id.
     */
    public String getId() {
        Optional<IdLiteralSymbol> symbol = getSpannedScope().resolveIdLiteralLocally("id");

        return unescapeMonticore(symbol.get().getAstNode().get().getStringLiteral().getValue());
    }

    /**
     * @return The name of the submission flair, if it exists.
     */
    public Optional<String> getLinkFlairText() {
        Optional<LinkFlairTextLiteralSymbol> symbol = getSpannedScope().resolveLinkFlairTextLiteralLocally("linkFlairText");

        if(symbol.isPresent())
            return Optional.of(unescapeMonticore(symbol.get().getAstNode().get().getStringLiteral().getValue()));
        else
            return Optional.empty();
    }

    /**
     * @return the subreddit the submission was made in.
     */
    public String getSubreddit() {
        Optional<SubredditLiteralSymbol> symbol = getSpannedScope().resolveSubredditLiteralLocally("subreddit");

        return symbol.get().getAstNode().get().getStringLiteral().getValue();
    }

    /**
     * @return True if this submission has been marked as NSFW.
     */
    public boolean isNsfw() {
        Optional<NsfwLiteralSymbol> symbol = getSpannedScope().resolveNsfwLiteralLocally("nsfw");

        return symbol.get().getAstNode().get().getBooleanLiteral().getValue();
    }

    /**
     * @return True if this submission has been marked as spoiler.
     */
    public boolean isSpoiler() {
        Optional<SpoilerLiteralSymbol> symbol = getSpannedScope().resolveSpoilerLiteralLocally("spoiler");

        return symbol.get().getAstNode().get().getBooleanLiteral().getValue();
    }

    /**
     * @return The upvotes of the submission minus the downvotes.
     */
    public int getScore() {
        Optional<ScoreLiteralSymbol> symbol = getSpannedScope().resolveScoreLiteralLocally("score");

        //#TODO getSource is bugged in 5.3.0
        ASTSignedNatLiteral ast = symbol.get().getAstNode().get().getSignedNatLiteral();

        return Integer.parseInt(ast.isNegative() ? "-" + ast.getDigits() : ast.getDigits());
    }

    /**
     * @return The title of this submission.
     */
    public String getTitle() {
        Optional<TitleLiteralSymbol> symbol = getSpannedScope().resolveTitleLiteralLocally("title");

        return unescapeMonticore(symbol.get().getAstNode().get().getStringLiteral().getValue());
    }

    /**
     * @return The timestamp when this submission was created.
     */
    public LocalDateTime getCreated() {
        String digits = getSpannedScope()
                .resolveCreatedLiteralLocally("created")
                .flatMap(CreatedLiteralSymbol::getAstNode)
                .map(ASTCreatedLiteral::getBasicLongLiteral)
                .map(ASTBasicLongLiteral::getDigits).orElseThrow();
        long value = Long.parseUnsignedLong(digits);

        return LocalDateTime.ofEpochSecond(value, 0, ZoneOffset.UTC);
    }

    /**
     * @return The text within the submission, if it exists.
     */
    public Optional<String> getSelfText() {
        Optional<SelfTextLiteralSymbol> symbol = getSpannedScope().resolveSelfTextLiteralLocally("selfText");

        if(symbol.isPresent())
            return Optional.of(unescapeMonticore(symbol.get().getAstNode().get().getStringLiteral().getValue()));
        else
            return Optional.empty();
    }

    /**
     * @return The thumbnail of this submission, if it exists.
     */
    public Optional<String> getThumbnail() {
        Optional<ThumbnailLiteralSymbol> symbol = getSpannedScope().resolveThumbnailLiteralLocally("thumbnail");

        if(symbol.isPresent())
            return Optional.of(unescapeMonticore(symbol.get().getAstNode().get().getStringLiteral().getValue()));
        else
            return Optional.empty();
    }

    /**
     * @return An absolute URL to this submission.
     */
    public String getUrl() {
        Optional<UrlLiteralSymbol> symbol = getSpannedScope().resolveUrlLiteralLocally("url");

        return unescapeMonticore(symbol.get().getAstNode().get().getStringLiteral().getValue());
    }

    /**
     * @return An URL to this submission relative to reddit.com.
     */
    @Override
    public String getPermalink(){
        Optional<PermalinkLiteralSymbol> symbol = getSpannedScope().resolvePermalinkLiteralLocally("permalink");

        return unescapeMonticore(symbol.get().getAstNode().get().getStringLiteral().getValue());
    }
    /**
     * @return A hash code based on the id of the submission.
     */
    @Override
    public int hashCode(){
        return getId().hashCode();
    }
    /**
     * Two submissions are equal if they have the same id.
     * @param o An object this submission is compared to.
     * @return True if the object is a submission with the same id.
     */
    @Override
    public boolean equals(Object o){
        if(o instanceof Submission){
            Submission submission = (Submission)o;
            return submission.getId().equals(this.getId());
        }else{
            return false;
        }
    }
}
